FROM python

# install environment dependencies
RUN apt-get update -yqq \
  && apt-get install -yqq --no-install-recommends \
    netcat \
  && apt-get -q clean


RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

# add app
COPY . /usr/src/app

# making the script executable
RUN chmod +x boot.sh

# add requirements
# COPY ./requirements.txt /usr/src/app/requirements.txt

# install requirements
RUN pip install --no-cache-dir -r requirements.txt
# RUN pip install -r requirements.txt

# EXPOSE 5000

# run server
# CMD ["python", "manage.py"]
# ENTRYPOINT ["./boot.sh"]
CMD ["./boot.sh"]
