version: '3'

services:
  web:
    # container_name: microblog
    build: .
      # context: .
      # dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 5001:5000
    # environment:
    #   - FLASK_APP=project/__init__.py
    #   - FLASK_DEBUG=1
