"""add language to posts

Revision ID: 85784d6adc55
Revises: 0afb42ec20ef
Create Date: 2018-05-18 07:13:06.905355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85784d6adc55'
down_revision = '0afb42ec20ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
